name: Bundle and Publish Sources

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build sources at Pages root
        run: npm run bundle

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: bundles
          clean: true
